// Generated by https://quicktype.io

export interface ICategoriesResponse {
    data: ICategoryData[];
}

export interface ICategoryData {
    id:          string;
    name:        string;
    slug:        string;
    image:       string;
    description: string;
}
