// Generated by https://quicktype.io

export interface ISimpleProductResponse {
    data: ISimpleProductData;
}

export interface ISimpleProductData {
    id:          string;
    name:        string;
    slug:        string;
    stock:       number;
    price:       number;
    description: string;
    category:    Category;
    images:      Image[];
}

interface Category {
    id:          string;
    name:        string;
    slug:        string;
    image:       string;
    description: string;
}

interface Image {
    id:  number;
    url: string;
}
